Whj/main rice 2
wooritech/woori-camp-mission-01 pull request #19
Opened 2024-01-29 02:43 UTC by Hjname

2024-01-29 08:28 UTC, onlydel commented on main.js
> +let slideWidth = slide.clientWidth;//슬라이드 크기 구하기 //clientWidth 요소의 가로값 가져오기
해당 행에 대한 주석은 코드 바로 위에 붙여주는게 일반적입니다.
예를들어

```js
// 슬라이드 크기 기록 변수
let slideWidth = ....
```

2024-01-29 08:31 UTC, Hjname commented on main.js
> +let slideWidth = slide.clientWidth;//슬라이드 크기 구하기 //clientWidth 요소의 가로값 가져오기
코드 사이에 주석이 너무 많이 들어가면 코드가 길어질까봐 뒤로 붙였었는데 다음부터는 규칙에 맞춰서 작성해 보겠습니다!

2024-01-29 08:34 UTC, onlydel commented on main.js
> +let slideWidth = slide.clientWidth;//슬라이드 크기 구하기 //clientWidth 요소의 가로값 가져오기
주석 많이 있어서 코드 이해하기 너무 좋네요. 👍

이 PR에서 한 번 다 수정해 보면 좋을것 같애요.

2024-01-29 08:36 UTC, onlydel requested changes
- [ ] 주석 정리하기

2024-01-29 08:44 UTC, Malloc72P requested changes
리뷰 완료했습니다.

- 요구사항과 다르게 구현된 부분이 있어서 리뷰 남깁니다
- 피그마에 디자인된 것 과 다른 폰트 사이즈를 가지는 경우가 좀 많은 것 같네요
- 일단 제가 찾은 부분은 리뷰로 남겼습니다. 그 외에도 있을 수 있으니, 재검토 부탁드려요 🚀

2024-01-29 08:44 UTC, Malloc72P commented on index.html
> +        </div>
### 피그마엔 패딩이 없지만, 구현된 화면엔 있습니다

#### 피그마 화면

- 아래와 같이, `가장 맛있는`, `시간 30일`엔 패딩이 없습니다. 그래서 가까이 붙어있어야 하는데, 구현된 화면엔 있습니다
<img width="638" alt="image" src="https://github.com/wooritech/wooricamp-mission/assets/41663269/dd5b7608-e3aa-44a9-8b78-76694e81a71d">

#### 실제 구현화면

![image](https://github.com/wooritech/wooricamp-mission/assets/41663269/fdb00a40-5344-421b-a113-f9bdcc7c5d6a)
- 피그마 디자인에 맞춰서 수정 부탁드립니다

2024-01-29 08:44 UTC, Malloc72P commented on index.html
> +        </div>
#### 폰트 크기가 요구사항과 다릅니다

#### 피그마 화면

![image](https://github.com/wooritech/wooricamp-mission/assets/41663269/ba0c7095-6f4b-4471-9209-afe7d79a168c)

![image](https://github.com/wooritech/wooricamp-mission/assets/41663269/ece404cb-c357-41de-b52c-629b18b8df19)

![image](https://github.com/wooritech/wooricamp-mission/assets/41663269/da814568-1410-490d-9f8b-ffaf8a3814d1)


- 읽기전용 화면에서도 폰트 사이즈는 볼 수 있습니다!
- 피그마에 디자인된 대로 폰트 사이즈를 맞춰주세요

2024-01-29 08:44 UTC, Malloc72P commented on index.html
> +          </div>
대쉬의 폰트 사이즈가 피그마와 다릅니다

![image](https://github.com/wooritech/wooricamp-mission/assets/41663269/ceb35736-a0a3-4a05-910c-0325865523f7)

수정 부탁드립니다

2024-01-29 08:45 UTC, Malloc72P commented on index.html
> +        </div>
The도 가운데 정렬이 되어야 합니다!

<img width="521" alt="image" src="https://github.com/wooritech/wooricamp-mission/assets/41663269/40f0f137-b49b-4320-8629-2837a53fd65e">

2024-01-29 08:54 UTC, Malloc72P commented on main.css
> +  align-items: center; /* 교차축(y) 정렬 */
👍

2024-01-29 08:56 UTC, Malloc72P commented on main.css
> +.rice_container {
클래스명만 봐도 어떤 요소에 대한 클래스인지 알 수 있어서 좋았습니다 👍

근데 클래스명에 일관성이 있으면 더 좋을 것 같아요

어떤 클래스에선 `-`를 사용하는데, 이곳에선 `_`를 사용하네요
```
ex) .header-line-two
```

둘 중 하나로 통일해주면 좋겠습니다!

2024-01-30 02:04 UTC, Hjname commented on main.css
> +.rice_container {
-로 통일하였습니다.

2024-01-30 02:05 UTC, Hjname commented on index.html
> +        </div>
코드 추가해서 문제 해결했습니다
```js
.rice .c {
  display: flex;
  justify-content: center;
}
```

2024-01-30 02:05 UTC, Hjname commented on index.html
> +        </div>
코드 추가해서 해결했습니다.
```js
* {
  margin: 0;
  padding: 0;
}
```

2024-01-30 02:05 UTC, Hjname commented on main.js
> +let slideWidth = slide.clientWidth;//슬라이드 크기 구하기 //clientWidth 요소의 가로값 가져오기
주석 위치 코드 위로 수정했습니다.

2024-01-30 08:10 UTC, Malloc72P requested changes
![image](https://github.com/wooritech/wooricamp-mission/assets/41663269/8a55cb26-27d2-488b-ae8f-32ff61ac4896)

main-rice-2 브랜치 최신버전을 받고 나서 위와 같은 에러가 발생합니다

확인바랍니다!

2024-01-30 08:15 UTC, Malloc72P commented on index.html
> +        </div>
이렇게 하면 요구사항을 만족할 수 있습니다만... 선택자로 *를 사용할 땐 주의하는게 좋겠습니다!

모든 요소에 적용이 되니까요!

다만, 마진과 패딩은 Hjname님이 작성하신것 처럼, 일단 0으로 초기화하고 작업해도 괜찮습니다.
저도 프로젝트 초기에 마진이랑 패딩은 0으로 초기화하고 시작하곤 합니다

2024-01-31 00:55 UTC, Hjname commented
> ![image](https://private-user-images.githubusercontent.com/41663269/300726718-8a55cb26-27d2-488b-ae8f-32ff61ac4896.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NjI3OTYsIm5iZiI6MTcwNjY2MjQ5NiwicGF0aCI6Ii80MTY2MzI2OS8zMDA3MjY3MTgtOGE1NWNiMjYtMjdkMi00ODhiLWFlOGYtMzJmZjYxYWM0ODk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDAwNTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzNjgwODc3MzZlOTQ2ZGZiZmVmYzcwOGJmY2UyYmYzNzYzZTI5NDlkNjRkZWZlYmExNTc4ZDc5YmIwYzVjYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tG-m4iX164ALhPsM_4qZfpTw0rNzN0OxIhAtMtCAcvI)
> 
> main-rice-2 브랜치 최신버전을 받고 나서 위와 같은 에러가 발생합니다
> 
> 캐로셀도 동작하지 않네요!
> 
> 확인바랍니다!

js 내용이 수정되지 않아서 발생했던 오류였습니다. 현재 수정 완료했습니다.

2024-01-31 01:18 UTC, Malloc72P approved these changes
정상동작 확인했습니다

2024-01-31 01:22 UTC, merged