두번째 페이지 헤더, 푸터 추가
wooritech/woori-camp-mission-01 pull request #26
Opened 2024-02-07 01:48 UTC by Hjname

### 두번째 페이지 html, css 결과물

- 헤더와 푸터는 이전에 작성한 내용을 가져와 사용
- 헤더의 클래스가 적용 되는 범위를 한정하기 위해 일부 내용 추가
- 각각의 아이템을 %단위로 지정하여 한줄에 들어가는 이미지의 수를 한정

<img width="1679" alt="image" src="https://github.com/wooritech/wooricamp-mission/assets/152573932/8f5cf27c-50bc-43d2-b4ad-e9817f3c06a8">

2024-02-07 05:23 UTC, onlydel requested changes
### 파일 이름 수정 요청

- 파일 이름 만들때도 규칙이 있습니다.
- 보통 이런걸 네이밍 컨벤션(naming convention) 이라고 표현 하는데,
- 일반적으로 개발에 사용되는 파일 이름을 만들때, 공백은 사용하지 않는 것이 원칙입니다.
- 보통은 오류를 발생시키지는 않지만, 때에 따라 오류가 발생할 여지도 있습니다.
- 👉 공백을 사용하는 파일을 수정해 주세요.

### css 파일의 중복 코드

중복 코드 제거는 JS 파일에만 해당되는 얘기는 아닙니다.
지금 보면 main.css 와 `Product list.css` 파일안에 중복 되는 스타일들이 많이 들어 있습니다.

- 이 중복 되는 코드들을 공통으로 사용할 하나의 파일에 모아서 합치고,
- 오직(used only) index.html, `Product list.html` 파일에서 사용되는 스타일만 각각의 파일로 만들고,
- 👉 공통으로 사용할 하나의 스타일 파일과 개별 스타일파일을 각각의 html 파일에 추가하는 방식으로 수정해 주세요.

2024-02-08 01:22 UTC, Hjname commented
> ### 파일 이름 수정 요청
> * 파일 이름 만들때도 규칙이 있습니다.
> * 보통 이런걸 네이밍 컨벤션(naming convention) 이라고 표현 하는데,
> * 일반적으로 개발에 사용되는 파일 이름을 만들때, 공백은 사용하지 않는 것이 원칙입니다.
> * 보통은 오류를 발생시키지는 않지만, 때에 따라 오류가 발생할 여지도 있습니다.
> * 👉 공백을 사용하는 파일을 수정해 주세요.
> 
> ### css 파일의 중복 코드
> 중복 코드 제거는 JS 파일에만 해당되는 얘기는 아닙니다. 지금 보면 main.css 와 `Product list.css` 파일안에 중복 되는 스타일들이 많이 들어 있습니다.
> 
> * 이 중복 되는 코드들을 공통으로 사용할 하나의 파일에 모아서 합치고,
> * 오직(used only) index.html, `Product list.html` 파일에서 사용되는 스타일만 각각의 파일로 만들고,
> * 👉 공통으로 사용할 하나의 스타일 파일과 개별 스타일파일을 각각의 html 파일에 추가하는 방식으로 수정해 주세요.

헤더와 푸터의 css를 분리한뒤 각각의 페이지에 적용하였습니다.

```js
@import url("header.css");
@import url("footer.css");
```

2024-02-08 01:33 UTC, onlydel requested changes
요구한 내용은 대부분 잘 변경된것 같습니다.
하지만, Naming Convention의 또다른 일반적 사항중 시작 문자의 대소문자에 대한 것도 있습니다.
어떻게 하면 좋을까요?

2024-02-08 01:44 UTC, Hjname commented
> 요구한 내용은 대부분 잘 변경된것 같습니다. 하지만, Naming Convention의 또다른 일반적 사항중 시작 문자의 대소문자에 대한 것도 있습니다. 어떻게 하면 좋을까요?

파일명 Product-list.html과 Product-list.css를 camel case로 변경하였습니다.

2024-02-08 05:06 UTC, onlydel requested changes
카멜 케이스도 나쁘지 않지만 이 프로젝트의 파일 이름 규칙은 아래 세가지를 기본으로 하기로 합시다.

- 파일명은 가능한 소문자를 사용한다.
- 단어와 단어 사이는 하이프(-)으로 연결 한다.
- 파일명은 최대한 짥게 만든다.

2024-02-08 05:15 UTC, onlydel approved these changes
잘했습니다.
이제 본격 적으로 중복 코드 제거 해봅시다.

2024-02-08 05:16 UTC, merged