우리펫푸드 페이지 전체 공용 헤더 작성&에러와 향후 수정
wooritech/woori-camp-mission-01 pull request #5
Opened 2024-01-19 07:44 UTC by Hjname

# 헤더 구현

- 동물 이름이 들어가는 자리 앞에 공백이 발생하여 해결하기 위해 시간이 들었습니다.
- 전체 화면으로 봤을떄 중앙에 만들어지지 않는 상태여서 수정할 계획입니다.
- 들어가 있는 색상을 완성 후 삭제할 예정입니다.

2024-01-19 07:51 UTC, Malloc72P reviewed
안녕하세요? 리뷰를 맡게 된 Malloc72P입니다

몇가지 질문사항이 있어서 코멘트 남겨드려요

### 질문1: 혹시 작업을 mission이라는 폴더 밑에서 하시는 이유가 있으신가요?

- 특별한 이유가 없다면, 랜딩페이지의 index.html을 루트 경로에 두면 좋을 것 같아요.

2024-01-19 07:52 UTC, Malloc72P commented on mission/index.html
> +      </a> -->
목적에 맞는 태그를 사용하셨군요!

처음 하면 div 태그만 사용해서 만들곤 하는데, 이렇게 한건 정말 좋은 것 같아요! 👍

2024-01-19 08:03 UTC, Malloc72P requested changes
앞서 코멘트 드린 내용처럼, 랜딩페이지의 index.html을 프로젝트 루트 경로로 옮겨주시면 좋을 것 같습니다.

혹시 mission 폴더에 두어야 하는 특별한 이유가 있으신 경우, 아래에 코멘트 달아주세요

그 외엔 조금 더 리뷰해보겠습니다.

그래서 Request changes 드리겠습니다 😈

2024-01-19 08:06 UTC, Hjname commented
> 안녕하세요? 리뷰를 맡게 된 Malloc72P입니다
> 
> 몇가지 질문사항이 있어서 코멘트 남겨드려요
> 
> ### 질문1: 혹시 작업을 mission이라는 폴더 밑에서 하시는 이유가 있으신가요?
> * 특별한 이유가 없다면, 랜딩페이지의 index.html을 루트 경로에 두면 좋을 것 같아요.

특별한 이유는 없습니다. 말씀해주신대로 한번 해보겠습니다.

2024-01-19 08:22 UTC, Malloc72P commented
> 안녕하세요? 리뷰를 맡게 된 Malloc72P입니다
> 
> 몇가지 질문사항이 있어서 코멘트 남겨드려요
> 
> ### 질문1: 혹시 작업을 mission이라는 폴더 밑에서 하시는 이유가 있으신가요?
> * 특별한 이유가 없다면, 랜딩페이지의 index.html을 루트 경로에 두면 좋을 것 같아요.

제가 질문만 남기고 왜 이렇게 생각했는지는 작성해드리질 않았네요 😅

이 프로젝트에선 VS-CODE의 `Live Server`라는 플러그인으로 페이지를 서비스하고 있어요.

이런 경우, 프로젝트 루트 경로를 웹서버의 루트로 사용하게 됩니다.
예를 들면, `http://localhost:5500`이라는 경로로 접속하면, 프로젝트 루트 경로에 있는 index.html이 제공되는거지요.
만약 지금처럼 mission 폴더 밑에 랜딩페이지의 index.html파일을 위치시키면, `http://localhost:5500`경로로 접속했을 때 404 not found 에러가 발생할꺼예요.

그래서 프로젝트 루트 경로에 랜딩페이지의 index.html을 위치시키는게 좋을 것 같습니다!

2024-01-19 08:35 UTC, Malloc72P requested changes
몇가지 추가 의견을 코멘트로 남겨드려요!

2024-01-19 08:35 UTC, Malloc72P commented on mission/?png/day02-1.png
폴더 이름이 `?png`로 시작하네요!

특수문자는 폴더명에 안넣어주는 편이 좋을 것 같아요
그리고 폴더명만 봐도, 아래의 이미지가 어떤 목적으로 사용되는지 알 수 있으면 좋을 것 같습니다!

2024-01-19 08:35 UTC, Malloc72P commented on mission/index.html
> +          <h2 href="logo">🦂 우리펫푸드</h2>
전갈 말고 고양이나 강아지 이모티콘을 사용하면 좋을 것 같아요!

개인적으로 좋아하는 동물이 있으면, 그 동물을 사용해주셔도 괜찮습니다! 🦆

2024-01-19 08:35 UTC, Malloc72P commented on mission/index.html
> +              <a href="javascript:void(0)">로그인</a>
`#` 대신에 `javascript:void(0)`를 앵커태그의 href속성값으로 사용해주셨군요!

혹시 왜 이렇게 작성했는지 알려주실 수 있나요?

2024-01-19 08:35 UTC, Malloc72P commented on mission/index.html
> +          <ul class="pet">
클래스명을 보고 해당 태그의 역할을 알 수 있으면 좋을 것 같아요!

ul태그는 자식요소로 li 태그를 가지니까, 
복수형태인 pets는 ul이, 단수형은 li태그가 사용해도 좋을 것 같아요

@hjname님은 어떻게 생각하시나요?

그리고 어떤 태그를 감싸는 태그에 이름을 지어주고 싶은 경우, 클래스명 뒤에 `wrapper`, 또는 `container`라는 이름을 자주 사용하곤 합니다

이렇게 작성해볼 수 도 있겠네요

```html

<div class="pets-wrapper">
  <ul class="pets">
    <li class="pet">
...
```

2024-01-19 08:35 UTC, Malloc72P commented on mission/index.html
> +            </li>
마이페이지라서 my라는 이름의 클래스를 사용한 것 같네요!

근데 me라는 클래스명을 사용하기보다, CSS 선택자(Selector)를 사용하면, 조금 더 효율적으로 작성할 수 있을 것 같아요!

css파일에 my, me라는 클래스명이 같이 있으면, 이 클래스가 어떤 역할을 하는지 알기 힘들 것 같네요

2024-01-21 04:16 UTC, Hjname commented on mission/index.html
> +              <a href="javascript:void(0)">로그인</a>
이번 미션에서는 작성하지 않지만 로그인 페이지를 작성하게 되면 주소를 연결해야 함으로 `javascript:void(0)` 를 사용하였습니다.

2024-01-22 00:46 UTC, Hjname commented
> 이런 경우, 프로젝트 루트 경로를 웹서버의 루트로 사용하게 됩니다. 예를 들면, `http://localhost:5500`이라는 경로로 접속하면, 프로젝트 루트 경로에 있는 index.html이 제공되는거지요. 만약 지금처럼 mission 폴더 밑에 랜딩페이지의 index.html파일을 위치시키면, `http://localhost:5500`경로로 접속했을 때 404 not found 에러가 발생할꺼예요.
> 
> 그래서 프로젝트 루트 경로에 랜딩페이지의 index.html을 위치시키는게 좋을 것 같습니다!

잘 모르겠는 점이 있어서 질문 남겨요!

랜딩페이지를 루트 경로로 옮기려고 했는데요

루트 경로에 이미 index,html파일이 있어요

옮기게 되면 이 파일을 지워야 할 텐데 상관없나요?

2024-01-22 00:57 UTC, Malloc72P commented
> > 이런 경우, 프로젝트 루트 경로를 웹서버의 루트로 사용하게 됩니다. 예를 들면, `http://localhost:5500`이라는 경로로 접속하면, 프로젝트 루트 경로에 있는 index.html이 제공되는거지요. 만약 지금처럼 mission 폴더 밑에 랜딩페이지의 index.html파일을 위치시키면, `http://localhost:5500`경로로 접속했을 때 404 not found 에러가 발생할꺼예요.
> > 그래서 프로젝트 루트 경로에 랜딩페이지의 index.html을 위치시키는게 좋을 것 같습니다!
> 
> 잘 모르겠는 점이 있어서 질문 남겨요!
> 
> 랜딩페이지를 루트 경로로 옮기려고 했는데요
> 
> 루트 경로에 이미 index,html파일이 있어요
> 
> 옮기게 되면 이 파일을 지워야 할 텐데 상관없나요?

넵! 기존에 있던 루트의 index.html은 사용하지 않으니, 삭제하셔도 됩니다!

2024-01-22 08:34 UTC, Malloc72P commented
리뷰해드린 내용에 대해서 아무런 피드백이 없네요...

해당 기능은 작업 중단된건가요?

만약 작업 중단된거면 코멘트를 달아주면 좋을 것 같네요

2024-01-22 08:37 UTC, Malloc72P commented on mission/main.css
> +  width: auto;
width의 기본값은 auto인데, 따로 auto라고 설정해주신 이유가 있나요?

2024-01-22 08:37 UTC, Hjname commented on mission/index.html
> +          <ul class="pet">
li에 클래스를 사용할 필요가 없어져서 삭제했고 ul에는 각각의 동물이 들어간다는 의미에서 pet을 넣었습니다

2024-01-23 01:37 UTC, Hjname commented on mission/main.css
> +  width: auto;
해당 위치에 해당값이 필요하다는것을 숙지하기위해 기본값도 작성하고자 하고있습니다.

2024-01-23 01:39 UTC, Hjname commented
헤더 수정 완료

- 리뷰받은 내용 수정
-  css head의 position값 변경

2024-01-23 04:02 UTC, Hjname commented on mission/?png/day02-1.png
폴더 이름을 readme-in-img로 변경하였습니다.
해당 폴더는 md를 정리하는데 필요한 이미지들을 모아놓은 폴더입니다.

2024-01-23 04:04 UTC, Hjname commented on mission/index.html
> +            </li>
my 클래스 명은 유지한 상태로 me를 my의 하위 구성이라고 알수 있도록 my-container로 변경하였습니다.

2024-01-23 04:05 UTC, Hjname commented
> 리뷰해드린 내용에 대해서 아무런 피드백이 없네요...
> 
> 해당 기능은 작업 중단된건가요?
> 
> 만약 작업 중단된거면 코멘트를 달아주면 좋을 것 같네요

해당 작업은 완료되었습니다.

2024-01-23 04:08 UTC, Malloc72P approved these changes
리뷰 완료했습니다 Approved 드릴께요~

첫번째 리뷰라서 많이 어려웠을텐데 고생 많으셨습니다!

![image](https://github.com/wooritech/wooricamp-mission/assets/41663269/e94d992b-bb30-48e8-b119-92ce38650cbc)

@Hjname 님이 직접 merge 버튼을 눌러서, 해당 풀리퀘스트를 완료해주세요!

2024-01-23 04:09 UTC, merged